[package]
name = "rust-cryptocurrency"
version = "0.1.0"
authors = ["Henry Boisdequin <65845077+henryboisdequin@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.2"
crypto-hash = "0.3.4"